import argparse
import datetime
import logging
import os
import sys

os.makedirs("output", exist_ok=True)

logging.basicConfig(
    filename="output/log.txt",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

parser = argparse.ArgumentParser()
parser.add_argument("--name", required=True)
parser.add_argument("--grade", type=int, required=True)
parser.add_argument("--bonus", required=True)
parser.add_argument("--exam_date", required=True)

args = parser.parse_args()

if args.grade < 0 or args.grade > 100:
    logging.error("Grade must be between 0 and 100")
    sys.exit("Grade must be between 0 and 100")

try:
    datetime.datetime.strptime(args.exam_date, "%Y-%m-%d")
except ValueError:
    logging.error("Date must be YYYY-MM-DD")
    sys.exit("Date must be YYYY-MM-DD")

bonus = args.bonus.lower() == "true"

final_grade = args.grade
if bonus:
    final_grade += 5
    if final_grade > 100:
        final_grade = 100

status = "PASSED 🎉" if final_grade >= 60 else "FAILED ❌"
status_color = "#00ff88" if final_grade >= 60 else "#ff4d4d"
grade_color = "#ffffff"

logging.info("Calculation completed")

html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Student Grade Report</title>
<style>
body {{
    margin: 0;
    font-family: 'Segoe UI', sans-serif;
    background: linear-gradient(135deg, #4facfe, #00f2fe);
    overflow: hidden;
    height: 100vh;
}}

.bubble {{
    position: absolute;
    border-radius: 50%;
    background: rgba(255,255,255,0.2);
    backdrop-filter: blur(5px);
    animation: float 20s infinite linear;
}}

@keyframes float {{
    from {{
        transform: translateY(100vh) scale(1);
    }}
    to {{
        transform: translateY(-10vh) scale(1.2);
    }}
}}

.card {{
    position: relative;
    z-index: 2;
    background: rgba(255,255,255,0.15);
    backdrop-filter: blur(20px);
    border-radius: 20px;
    padding: 40px;
    width: 450px;
    color: white;
    box-shadow: 0 10px 30px rgba(0,0,0,0.3);
    margin: auto;
    top: 50%;
    transform: translateY(-50%);
}}

h1 {{
    text-align: center;
}}

.grade {{
    font-size: 70px;
    text-align: center;
    font-weight: bold;
    color: {grade_color};
}}

.status {{
    text-align: center;
    font-weight: bold;
    font-size: 18px;
    margin-bottom: 20px;
    color: {status_color};
}}

.info p {{
    margin: 6px 0;
}}

.footer {{
    margin-top: 20px;
    text-align: center;
    font-size: 13px;
    opacity: 0.8;
}}
</style>
</head>
<body>

<div class="bubble" style="width:100px;height:100px;left:10%;animation-duration:25s;"></div>
<div class="bubble" style="width:150px;height:150px;left:70%;animation-duration:30s;"></div>
<div class="bubble" style="width:80px;height:80px;left:40%;animation-duration:18s;"></div>
<div class="bubble" style="width:120px;height:120px;left:85%;animation-duration:22s;"></div>
<div class="bubble" style="width:60px;height:60px;left:25%;animation-duration:15s;"></div>

<div class="card">
<h1>📊 Student Report</h1>

<div class="grade">{final_grade}</div>
<div class="status">{status}</div>

<div class="info">
<p><strong>Name:</strong> {args.name}</p>
<p><strong>Original Grade:</strong> {args.grade}</p>
<p><strong>Bonus Applied:</strong> {bonus}</p>
<p><strong>Exam Date:</strong> {args.exam_date}</p>
<p><strong>Generated:</strong> {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
</div>

<div class="footer">
Generated by Jenkins Pipeline 🚀
</div>
</div>

</body>
</html>
"""

with open("output/report.html", "w", encoding="utf-8") as f:
    f.write(html)

print("Report generated successfully")
