import argparse
import datetime
import logging
import os
import sys

os.makedirs("output", exist_ok=True)

logging.basicConfig(
    filename="output/log.txt",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

parser = argparse.ArgumentParser()

parser.add_argument("--name", required=True)
parser.add_argument("--grade", type=int, required=True)
parser.add_argument("--bonus", required=True)
parser.add_argument("--exam_date", required=True)

args = parser.parse_args()

if args.grade < 0 or args.grade > 100:
    logging.error("Grade must be between 0 and 100")
    sys.exit("Grade must be between 0 and 100")

try:
    datetime.datetime.strptime(args.exam_date, "%Y-%m-%d")
except ValueError:
    logging.error("Date must be YYYY-MM-DD")
    sys.exit("Date must be YYYY-MM-DD")

bonus = args.bonus.lower() == "true"

final_grade = args.grade

if bonus:
    final_grade += 5
    if final_grade > 100:
        final_grade = 100

status = "Passed" if final_grade >= 60 else "Failed"

logging.info("Calculation completed")

color = "#28a745" if status == "Passed" else "#dc3545"

html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Student Grade Report</title>
    <style>
        body {{
            font-family: Arial, sans-serif;
            background-color: #f4f6f9;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }}
        .card {{
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            width: 400px;
        }}
        h2 {{
            text-align: center;
        }}
        table {{
            width: 100%;
            border-collapse: collapse;
        }}
        td {{
            padding: 8px;
        }}
        .status {{
            font-weight: bold;
            color: {color};
        }}
        .footer {{
            margin-top: 15px;
            text-align: center;
            font-size: 12px;
            color: gray;
        }}
    </style>
</head>
<body>
    <div class="card">
        <h2>Student Grade Report</h2>
        <table>
            <tr><td><strong>Name:</strong></td><td>{args.name}</td></tr>
            <tr><td><strong>Original Grade:</strong></td><td>{args.grade}</td></tr>
            <tr><td><strong>Bonus Applied:</strong></td><td>{bonus}</td></tr>
            <tr><td><strong>Final Grade:</strong></td><td>{final_grade}</td></tr>
            <tr><td><strong>Status:</strong></td><td class="status">{status}</td></tr>
            <tr><td><strong>Exam Date:</strong></td><td>{args.exam_date}</td></tr>
        </table>
        <div class="footer">
            Generated by Jenkins Pipeline 🚀
        </div>
    </div>
</body>
</html>
"""
