import argparse
import datetime
import logging
import os
import sys

os.makedirs("output", exist_ok=True)

logging.basicConfig(
    filename="output/log.txt",
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)

parser = argparse.ArgumentParser()
parser.add_argument("--name", required=True)
parser.add_argument("--grade", type=int, required=True)
parser.add_argument("--bonus", required=True)
parser.add_argument("--exam_date", required=True)

args = parser.parse_args()

if args.grade < 0 or args.grade > 100:
    logging.error("Grade must be between 0 and 100")
    sys.exit("Grade must be between 0 and 100")

try:
    datetime.datetime.strptime(args.exam_date, "%Y-%m-%d")
except ValueError:
    logging.error("Date must be YYYY-MM-DD")
    sys.exit("Date must be YYYY-MM-DD")

bonus = args.bonus.lower() == "true"

final_grade = args.grade
if bonus:
    final_grade += 5
    if final_grade > 100:
        final_grade = 100

passed = final_grade >= 60
status = "PASSED 🎉" if passed else "FAILED ❌"
status_color = "#00ff88" if passed else "#ff4d4d"

logging.info("Calculation completed")

confetti_script = ""

if passed:
    confetti_script = """
<script>
const colors = ["#ff4d4d","#4facfe","#00ff88","#ffcc00","#ff66ff"];
for(let i=0;i<120;i++){
  const conf = document.createElement("div");
  conf.style.position="fixed";
  conf.style.width="8px";
  conf.style.height="8px";
  conf.style.background=colors[Math.floor(Math.random()*colors.length)];
  conf.style.left=Math.random()*100+"vw";
  conf.style.top="-10px";
  conf.style.opacity=Math.random();
  conf.style.borderRadius="50%";
  conf.style.zIndex="9999";
  document.body.appendChild(conf);

  let fall=Math.random()*5+3;
  conf.animate([
    { transform:"translateY(0) rotate(0deg)" },
    { transform:`translateY(100vh) rotate(${Math.random()*720}deg)` }
  ],{
    duration:fall*1000,
    iterations:1
  });

  setTimeout(()=>conf.remove(), fall*1000);
}
</script>
"""

html = f"""<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Student Grade Report</title>
<style>
body {{
    margin: 0;
    font-family: 'Segoe UI', sans-serif;
    background: linear-gradient(135deg, #4facfe, #00f2fe);
    overflow: hidden;
    height: 100vh;
}}

.card {{
    position: relative;
    z-index: 2;
    background: rgba(255,255,255,0.15);
    backdrop-filter: blur(20px);
    border-radius: 20px;
    padding: 40px;
    width: 450px;
    color: white;
    box-shadow: 0 10px 30px rgba(0,0,0,0.3);
    margin: auto;
    top: 50%;
    transform: translateY(-50%);
}}

h1 {{
    text-align: center;
}}

.grade {{
    font-size: 70px;
    text-align: center;
    font-weight: bold;
}}

.status {{
    text-align: center;
    font-weight: bold;
    font-size: 18px;
    margin-bottom: 20px;
    color: {status_color};
}}

.info p {{
    margin: 6px 0;
}}

.footer {{
    margin-top: 20px;
    text-align: center;
    font-size: 13px;
    opacity: 0.8;
}}
</style>
</head>
<body>

<div class="card">
<h1>📊 Student Report</h1>

<div class="grade">{final_grade}</div>
<div class="status">{status}</div>

<div class="info">
<p><strong>Name:</strong> {args.name}</p>
<p><strong>Original Grade:</strong> {args.grade}</p>
<p><strong>Bonus Applied:</strong> {bonus}</p>
<p><strong>Exam Date:</strong> {args.exam_date}</p>
<p><strong>Generated:</strong> {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
</div>

<div class="footer">
Generated by Jenkins Pipeline 🚀
</div>
</div>

{confetti_script}

</body>
</html>
"""

with open("output/report.html", "w", encoding="utf-8") as f:
    f.write(html)

print("Report generated successfully")
